version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    target-branch: development
    reviewers:
      - SauloNunesDev
    assignees:
      - SauloNunesDev
    labels:
      - 'actions'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
    target-branch: development
    reviewers:
      - SauloNunesDev
    assignees:
      - SauloNunesDev
    commit-message:
      prefix: 'npm'
      include: 'scope'
    labels:
      - 'npm'
      - 'dependencies'
    versioning-strategy: increase-if-necessary
