name: Test

env:
  CI: true

on:
  pull_request:
    branches: [main, development]

  push:
    branches: [main, development]

jobs:
  cancel_previous-test:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

  test:
    runs-on: ubuntu-18.04
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Set Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com
        env:
          RUNNER_TEMP: '/tmp/'

      - name: Cache Node Modules
        uses: actions/cache@v2.1.4
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('./package-lock.json') }}

      - name: Install Node Modules
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Run Coverage
        run: npm run codecov

      - name: Building Project
        run: npm run build:dev

      - name: Codecov Action
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage/coverage-final.json
          token: ${{ secrets.CODECOV_TOKEN }}
